### PR TITLE
Fixes "Update 05-mysql-queries.md"

### PR DESCRIPTION
**Pull request by baghelnk10**
Fixes from hsf-training/hsf-training-databases-basics#40

### CODE REVIEW

**Comment by baghelnk10** [comment]
Hi @michmx  ,
I apologize for merging the last MR without any prior notification. I mistakenly merged the previous one due to issues with pushing the changes from my terminal ( indicating I didn't have permissions). I have revert the previous one for your review. Please take a look.

Thank you!

**Review by michmx — APPROVED** [review]
Thanks for the prompt action!

**Comment by michmx** [comment]
@all-contributors add @baghelnk10 for content

**Comment by michmx** [comment]
@all-contributors add @baghelnk10 for content

**Pull request merged**
